# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Unit_tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out Git repository
    
    - uses: actions/setup-node@v3
      name: Set up Node.js
      with:
        node-version: 18
        cache: 'yarn'
    
    - name: Install Node.js dependencies
      run: yarn

    - name: Run tests
      run: yarn test
